name: workflow all branches

on:
  push:
    branches:
      - '*'
      - '*/*'




# Define jobs for the workflow
jobs:
# Job: Build
  build:
    runs-on: ubuntu-latest
# Steps for the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build