name: workflow gitub pages

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
      # Steps for the deploy job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build
      - name: deploy
        uses: actions/deploy-pages@v3
      - name: Deploy to  gh-pages
        run: npm run deploy -- -m "Deploy React app to GitHub Pages"



